sudo: required

language: php

services:
  - docker

env:
  global:
    - DOCKER_REPO: 9jkh/mamicleaner
    # DOCKER_USERNAME
    - secure: "LMLUqfrIirVcw5RsbzVy2s5pxeuphfpEC1lEx7Vf98q/m5nRxPoqxfVEBq1XJddcyj5ea93ogUFE0X8qV5BQvtqj7v5JRVLdWWVAmCOR2RLave2T863WTcqAGo0XX/MCUFgZuNzvcA5VlqA6GpEDZjvAZwd/VLuhNzKZayESPANmcWGm+18Nt6XDXsRm5h2qStk1IBG971/gUJL+lr6UT5JnsltEfp0iWYfOaVQgLcDJ2FXfQNQiUCbTO26IH674qgkyU8ivmKN39quG19/R/NPPfliXsHfpqZO63vcs+yrfKhFpPkC60+vLt/1utnScGXHyXrYy8qHSnLvtfTPI4dsciF4qnDT6F+3AXe3aZz57rQuaNfbb0URLXSgD3iDk5xZklfN2oXJ9ezuQskfquUrbfDL1bTnwN7RtNBJdARDSTTEIQS3al/udC5ekFzgCvSiDYpwEZB+f+4e4ecrtt+EVeOwIksFOz/YFBB+ELJpeDgH9MSBiefjo1GyO9zwBS1TfPdsLuXuNIf+ImaNe3L2Cya4iGrIKeuHFhAFubN57B1kx/REYS/j7LiKPyDvZC7dDOUWB4r6K7hZAtOaflUajOUCLILXI0aYQ/sSIM7J/hgF0YCgMxl53bhvINFUzwYWVew4bvGQ98xLHdfT3mmg1PjeXZvbj6WpUdFFa85k="
    # DOCKER_PASSWORD
    - secure: "tukRqqbM0wlUtiqOLObuWlCFPCzDdx8O2JFKj9irclZmzzBJUeb+CL/6Wunf3jHBUR4hSgfO2coxZbWVqHxNmErOeROiMKBG7OGkJ2JOgpL9jX4W/J7+m9EWgEqaxQj3oUqFlbQ9JvW9Lu0Zp4bAsmv/pcSyKpoAYuN27T0HyumkU5xLu+2HNsAc2NaBeeLSUfujTFA1Nze8ijLkyzNsGyMzvtLb7YG80qiGjL8m3TfoUhCd8SLbXeQf/5DosZP/+H+GgN1tAsVL3QOgUMcxLh9JXHuNPWnBDpBll3syD6Is24+Q4zwwE7gblfnmDFGksfhhAkWXP1PsZNvtwFPn0o+qBzFva+gFxCKS9nza+7m1ivK1hynzO21tirqNpRWtu3c7IiSnBISVeGk2yjAiNyFFBNzxN19xuWUzTbHsBJ5+fW2Kmj5gKEuuxe1oTp/UwdBOq5ERJ6mHcNuO8Z2iXSUQqlM1vA4cIaNnWX8hl1IOM92J2sEqjA+YVZr3yAgXgH3SQKVNhZp3PVh80sF0/ekZHdst5QJnMPwvXwc0+X8pdPSbqQl5uqGJb/yHBxw/EeGFCys1JlPE6m+1x3Na5cq3xhvOVwlvmWjoeTySMAVSj4sWrbB8/zlhOVhZr/BM8wb1FhZUu8Vaot36qtW3qkdYZe+0aqv2m6SDyLA1fDs="

matrix:
  include:
    - php: 7.3
    - php: 7.2
      env: DEPLOY=true
    - php: 7.1

deploy:
  - provider: releases
    api_key:
      secure: CNwhY3ODgyYF0/HejfV5sIw2/GfJCfL9WM06FGGZEzOcxlVct3ixaTqYRhvelHqrOGdeTNA327csWueKqvVkjueIL2ZlqT+ABqcOraRYdYvba+DF24lbzIMEGrb6Ob3zDiaQfZrBYn9Guxnk9LB4eQoDfT9mkILgdeYo4SMLoW4lkrO7fajmr/6b5c5L/JWKtqcSudcwQNCYgDcSgem0R7gpWeVW+M5wV8fAQXFF1EGmjV1mMmFhmez/Z4EEEnZb0JWDM+MonHAxpRrf03CwjfAtFkMjjP3X8O+vaJ1eSnwgwiJ/Gjky3eCy7JH2GXSEGTEnE3q5Nu148Mfv3Ip9oqTAeJt7qEJL6uJu5057IoSCZ03LDBPqAlTEPkQWErgPsTDs7XWnUoU/YUfv6HF+CQ+qrakY8KzFWjJpDuuZO2GgDSJjWca6EaOs4DL/KeRLMsBtmznnyAUcEk+8Xfm5gOZuxAfs6BhDieCffh45I8Oguw5bpx8+dWi0ZptKxW2+soTLv9Vt69O6tHiucU03C0jliYF/Rzyj0qFUYFWNVOSLY4OiKYmX3aD7xXo9i3kJ2htdFp81vVWkyBCIDJJoQ3312AD5SvpHHyAxfy8j/SWce6os8EZ8XRzry44MRmyMe3FgYf9RfLv3wSPmSEMeH0Yq2a47aPvRyFKWzCotP+s=
    file: mamicleaner.phar
    on:
      tags: true
      condition: $DEPLOY = true
    skip_cleanup: true

  - provider: script
    script: "./push.sh"
    on:
      branch: master
      condition: $DEPLOY = true
    skip_cleanup: true

  - provider: script
    script: "./push.sh"
    on:
      tags: true
      condition: $DEPLOY = true
    skip_cleanup: true

script: "./build.sh"
